/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as StayIndexRouteImport } from './routes/stay.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppBillsRouteImport } from './routes/_authenticated/app.bills'
import { Route as AuthenticatedAppBookRouteImport } from './routes/_authenticated/app.book'
import { Route as AuthenticatedAppChainRouteImport } from './routes/_authenticated/app.chain'
import { Route as AuthenticatedAppGuestsRouteImport } from './routes/_authenticated/app.guests'
import { Route as AuthenticatedAppMenuRouteImport } from './routes/_authenticated/app.menu'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppRoomsRouteImport } from './routes/_authenticated/app.rooms'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as StayHIdRouteImport } from './routes/stay.h.$id'
import { Route as StayRTokenRouteImport } from './routes/stay.r.$token'
import { Route as AuthenticatedAppBillIdRouteImport } from './routes/_authenticated/app.bill.$id'
import { Route as AuthenticatedAppRoomIdRouteImport } from './routes/_authenticated/app.room.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StayIndexRoute = StayIndexRouteImport.update({
  id: '/stay/',
  path: '/stay/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBillsRoute = AuthenticatedAppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBookRoute = AuthenticatedAppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChainRoute = AuthenticatedAppChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGuestsRoute = AuthenticatedAppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMenuRoute = AuthenticatedAppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoomsRoute = AuthenticatedAppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const StayHIdRoute = StayHIdRouteImport.update({
  id: '/stay/h/$id',
  path: '/stay/h/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRTokenRoute = StayRTokenRouteImport.update({
  id: '/stay/r/$token',
  path: '/stay/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppBillIdRoute = AuthenticatedAppBillIdRouteImport.update({
  id: '/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoomIdRoute = AuthenticatedAppRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/stay/': typeof StayIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/bills': typeof AuthenticatedAppBillsRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/chain': typeof AuthenticatedAppChainRoute
  '/app/guests': typeof AuthenticatedAppGuestsRoute
  '/app/menu': typeof AuthenticatedAppMenuRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/rooms': typeof AuthenticatedAppRoomsRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/stay/h/$id': typeof StayHIdRoute
  '/stay/r/$token': typeof StayRTokenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/bill/$id': typeof AuthenticatedAppBillIdRoute
  '/app/room/$id': typeof AuthenticatedAppRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/stay': typeof StayIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/bills': typeof AuthenticatedAppBillsRoute
  '/app/book': typeof AuthenticatedAppBookRoute
  '/app/chain': typeof AuthenticatedAppChainRoute
  '/app/guests': typeof AuthenticatedAppGuestsRoute
  '/app/menu': typeof AuthenticatedAppMenuRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/rooms': typeof AuthenticatedAppRoomsRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/stay/h/$id': typeof StayHIdRoute
  '/stay/r/$token': typeof StayRTokenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/bill/$id': typeof AuthenticatedAppBillIdRoute
  '/app/room/$id': typeof AuthenticatedAppRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/stay/': typeof StayIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/bills': typeof AuthenticatedAppBillsRoute
  '/_authenticated/app/book': typeof AuthenticatedAppBookRoute
  '/_authenticated/app/chain': typeof AuthenticatedAppChainRoute
  '/_authenticated/app/guests': typeof AuthenticatedAppGuestsRoute
  '/_authenticated/app/menu': typeof AuthenticatedAppMenuRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/rooms': typeof AuthenticatedAppRoomsRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/stay/h/$id': typeof StayHIdRoute
  '/stay/r/$token': typeof StayRTokenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/bill/$id': typeof AuthenticatedAppBillIdRoute
  '/_authenticated/app/room/$id': typeof AuthenticatedAppRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/stay/'
    | '/app/admin'
    | '/app/bills'
    | '/app/book'
    | '/app/chain'
    | '/app/guests'
    | '/app/menu'
    | '/app/orders'
    | '/app/rooms'
    | '/app/scan'
    | '/app/settings'
    | '/stay/h/$id'
    | '/stay/r/$token'
    | '/app/'
    | '/app/bill/$id'
    | '/app/room/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/stay'
    | '/app/admin'
    | '/app/bills'
    | '/app/book'
    | '/app/chain'
    | '/app/guests'
    | '/app/menu'
    | '/app/orders'
    | '/app/rooms'
    | '/app/scan'
    | '/app/settings'
    | '/stay/h/$id'
    | '/stay/r/$token'
    | '/app'
    | '/app/bill/$id'
    | '/app/room/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/stay/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/bills'
    | '/_authenticated/app/book'
    | '/_authenticated/app/chain'
    | '/_authenticated/app/guests'
    | '/_authenticated/app/menu'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/rooms'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/settings'
    | '/stay/h/$id'
    | '/stay/r/$token'
    | '/_authenticated/app/'
    | '/_authenticated/app/bill/$id'
    | '/_authenticated/app/room/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StayIndexRoute: typeof StayIndexRoute
  StayHIdRoute: typeof StayHIdRoute
  StayRTokenRoute: typeof StayRTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/stay/': {
      id: '/stay/'
      path: '/stay'
      fullPath: '/stay/'
      preLoaderRoute: typeof StayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bills': {
      id: '/_authenticated/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AuthenticatedAppBillsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/book': {
      id: '/_authenticated/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AuthenticatedAppBookRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chain': {
      id: '/_authenticated/app/chain'
      path: '/chain'
      fullPath: '/app/chain'
      preLoaderRoute: typeof AuthenticatedAppChainRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/guests': {
      id: '/_authenticated/app/guests'
      path: '/guests'
      fullPath: '/app/guests'
      preLoaderRoute: typeof AuthenticatedAppGuestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/menu': {
      id: '/_authenticated/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AuthenticatedAppMenuRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rooms': {
      id: '/_authenticated/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AuthenticatedAppRoomsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/stay/h/$id': {
      id: '/stay/h/$id'
      path: '/stay/h/$id'
      fullPath: '/stay/h/$id'
      preLoaderRoute: typeof StayHIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/r/$token': {
      id: '/stay/r/$token'
      path: '/stay/r/$token'
      fullPath: '/stay/r/$token'
      preLoaderRoute: typeof StayRTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/bill/$id': {
      id: '/_authenticated/app/bill/$id'
      path: '/bill/$id'
      fullPath: '/app/bill/$id'
      preLoaderRoute: typeof AuthenticatedAppBillIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/room/$id': {
      id: '/_authenticated/app/room/$id'
      path: '/room/$id'
      fullPath: '/app/room/$id'
      preLoaderRoute: typeof AuthenticatedAppRoomIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppBillsRoute: typeof AuthenticatedAppBillsRoute
  AuthenticatedAppBookRoute: typeof AuthenticatedAppBookRoute
  AuthenticatedAppChainRoute: typeof AuthenticatedAppChainRoute
  AuthenticatedAppGuestsRoute: typeof AuthenticatedAppGuestsRoute
  AuthenticatedAppMenuRoute: typeof AuthenticatedAppMenuRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppRoomsRoute: typeof AuthenticatedAppRoomsRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBillIdRoute: typeof AuthenticatedAppBillIdRoute
  AuthenticatedAppRoomIdRoute: typeof AuthenticatedAppRoomIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppBillsRoute: AuthenticatedAppBillsRoute,
  AuthenticatedAppBookRoute: AuthenticatedAppBookRoute,
  AuthenticatedAppChainRoute: AuthenticatedAppChainRoute,
  AuthenticatedAppGuestsRoute: AuthenticatedAppGuestsRoute,
  AuthenticatedAppMenuRoute: AuthenticatedAppMenuRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppRoomsRoute: AuthenticatedAppRoomsRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBillIdRoute: AuthenticatedAppBillIdRoute,
  AuthenticatedAppRoomIdRoute: AuthenticatedAppRoomIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StayIndexRoute: StayIndexRoute,
  StayHIdRoute: StayHIdRoute,
  StayRTokenRoute: StayRTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
